import ExtendableError from '../exception';

throw ExtendableError('hello')
